apiVersion: apps/v1
kind: Deployment
metadata:
  name: readservice
  namespace: bitly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readservice
  template:
    metadata:
      labels:
        app: readservice
    spec:
      containers:
      - name: readservice
        image: bitly-readservice:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: USE_HTTPS_REDIRECT
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: readservice
  namespace: bitly
spec:
  selector:
    app: readservice
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
