apiVersion: apps/v1
kind: Deployment
metadata:
  name: writeservice
  namespace: bitly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writeservice
  template:
    metadata:
      labels:
        app: writeservice
    spec:
      containers:
      - name: writeservice
        image: bitly-writeservice:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: USE_HTTPS_REDIRECT
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: writeservice
  namespace: bitly
spec:
  selector:
    app: writeservice
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
